export const PRACTICE_AUTH_CONSTANTS = {
  LOGIN_REQUEST: 'PRACTICE/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'PRACTICE/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'PRACTICE/LOGIN_FAILURE',
  LOGOUT: 'PRACTICE/LOGOUT',
  REGISTER_REQUEST: 'PRACTICE/REGISTER_REQUEST',
  REGISTER_SUCCESS: 'PRACTICE/REGISTER_SUCCESS',
  REGISTER_FAILURE: 'PRACTICE/REGISTER_FAILURE',
  SET_PRACTICE: 'PRACTICE/SET_PRACTICE',
  UPDATE_PRACTICE: 'PRACTICE/UPDATE_PRACTICE',
  SET_LOADING: 'PRACTICE/SET_LOADING',
  CLEAR_ERROR: 'PRACTICE/CLEAR_ERROR',
  SET_TOKEN: 'PRACTICE/SET_TOKEN',
  REFRESH_TOKEN: 'PRACTICE/REFRESH_TOKEN',
} as const;

export const PRACTICE_APPOINTMENT_CONSTANTS = {
  FETCH_APPOINTMENTS: 'PRACTICE/APPOINTMENTS/FETCH',
  FETCH_APPOINTMENTS_SUCCESS: 'PRACTICE/APPOINTMENTS/FETCH_SUCCESS',
  FETCH_APPOINTMENTS_FAILURE: 'PRACTICE/APPOINTMENTS/FETCH_FAILURE',
  CREATE_APPOINTMENT: 'PRACTICE/APPOINTMENTS/CREATE',
  CREATE_APPOINTMENT_SUCCESS: 'PRACTICE/APPOINTMENTS/CREATE_SUCCESS',
  CREATE_APPOINTMENT_FAILURE: 'PRACTICE/APPOINTMENTS/CREATE_FAILURE',
  UPDATE_APPOINTMENT: 'PRACTICE/APPOINTMENTS/UPDATE',
  UPDATE_APPOINTMENT_SUCCESS: 'PRACTICE/APPOINTMENTS/UPDATE_SUCCESS',
  UPDATE_APPOINTMENT_FAILURE: 'PRACTICE/APPOINTMENTS/UPDATE_FAILURE',
  CANCEL_APPOINTMENT: 'PRACTICE/APPOINTMENTS/CANCEL',
  CANCEL_APPOINTMENT_SUCCESS: 'PRACTICE/APPOINTMENTS/CANCEL_SUCCESS',
  CANCEL_APPOINTMENT_FAILURE: 'PRACTICE/APPOINTMENTS/CANCEL_FAILURE',
  CONFIRM_APPOINTMENT: 'PRACTICE/APPOINTMENTS/CONFIRM',
  COMPLETE_APPOINTMENT: 'PRACTICE/APPOINTMENTS/COMPLETE',
  SET_SELECTED_APPOINTMENT: 'PRACTICE/APPOINTMENTS/SET_SELECTED',
} as const;

export const PRACTICE_PATIENT_CONSTANTS = {
  FETCH_PATIENTS: 'PRACTICE/PATIENTS/FETCH',
  FETCH_PATIENTS_SUCCESS: 'PRACTICE/PATIENTS/FETCH_SUCCESS',
  FETCH_PATIENTS_FAILURE: 'PRACTICE/PATIENTS/FETCH_FAILURE',
  SEARCH_PATIENTS: 'PRACTICE/PATIENTS/SEARCH',
  ADD_PATIENT: 'PRACTICE/PATIENTS/ADD',
  ADD_PATIENT_SUCCESS: 'PRACTICE/PATIENTS/ADD_SUCCESS',
  ADD_PATIENT_FAILURE: 'PRACTICE/PATIENTS/ADD_FAILURE',
  UPDATE_PATIENT: 'PRACTICE/PATIENTS/UPDATE',
  DELETE_PATIENT: 'PRACTICE/PATIENTS/DELETE',
  SET_SELECTED_PATIENT: 'PRACTICE/PATIENTS/SET_SELECTED',
} as const;

export const PRACTICE_SETTINGS_CONSTANTS = {
  FETCH_SETTINGS: 'PRACTICE/SETTINGS/FETCH',
  FETCH_SETTINGS_SUCCESS: 'PRACTICE/SETTINGS/FETCH_SUCCESS',
  UPDATE_SETTINGS: 'PRACTICE/SETTINGS/UPDATE',
  UPDATE_SETTINGS_SUCCESS: 'PRACTICE/SETTINGS/UPDATE_SUCCESS',
  UPDATE_SETTINGS_FAILURE: 'PRACTICE/SETTINGS/UPDATE_FAILURE',
  SETTINGS_ERROR: 'PRACTICE/SETTINGS/ERROR',
} as const;

export const PRACTICE_NOTIFICATION_CONSTANTS = {
  FETCH_NOTIFICATIONS: 'PRACTICE/NOTIFICATIONS/FETCH',
  FETCH_NOTIFICATIONS_SUCCESS: 'PRACTICE/NOTIFICATIONS/FETCH_SUCCESS',
  MARK_AS_READ: 'PRACTICE/NOTIFICATIONS/MARK_AS_READ',
  MARK_ALL_AS_READ: 'PRACTICE/NOTIFICATIONS/MARK_ALL_AS_READ',
} as const;

export const PRACTICE_DASHBOARD_CONSTANTS = {
  FETCH_DASHBOARD_STATS: 'PRACTICE/DASHBOARD/FETCH_STATS',
  FETCH_DASHBOARD_STATS_SUCCESS: 'PRACTICE/DASHBOARD/FETCH_STATS_SUCCESS',
  FETCH_DASHBOARD_STATS_FAILURE: 'PRACTICE/DASHBOARD/FETCH_STATS_FAILURE',
} as const;
