export const SUPERADMIN_AUTH_CONSTANTS = {
  LOGIN_REQUEST: 'SUPERADMIN/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'SUPERADMIN/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'SUPERADMIN/LOGIN_FAILURE',
  LOGOUT: 'SUPERADMIN/LOGOUT',
  SET_SUPERADMIN: 'SUPERADMIN/SET_SUPERADMIN',
  SET_LOADING: 'SUPERADMIN/SET_LOADING',
  CLEAR_ERROR: 'SUPERADMIN/CLEAR_ERROR',
} as const;

export const SUPERADMIN_PRACTICES_CONSTANTS = {
  FETCH_PRACTICES: 'SUPERADMIN/PRACTICES/FETCH',
  FETCH_PRACTICES_SUCCESS: 'SUPERADMIN/PRACTICES/FETCH_SUCCESS',
  FETCH_PRACTICES_FAILURE: 'SUPERADMIN/PRACTICES/FETCH_FAILURE',
  APPROVE_PRACTICE: 'SUPERADMIN/PRACTICES/APPROVE',
  APPROVE_PRACTICE_SUCCESS: 'SUPERADMIN/PRACTICES/APPROVE_SUCCESS',
  REJECT_PRACTICE: 'SUPERADMIN/PRACTICES/REJECT',
  REJECT_PRACTICE_SUCCESS: 'SUPERADMIN/PRACTICES/REJECT_SUCCESS',
  SUSPEND_PRACTICE: 'SUPERADMIN/PRACTICES/SUSPEND',
  SUSPEND_PRACTICE_SUCCESS: 'SUPERADMIN/PRACTICES/SUSPEND_SUCCESS',
  ACTIVATE_PRACTICE: 'SUPERADMIN/PRACTICES/ACTIVATE',
  ACTIVATE_PRACTICE_SUCCESS: 'SUPERADMIN/PRACTICES/ACTIVATE_SUCCESS',
  DELETE_PRACTICE: 'SUPERADMIN/PRACTICES/DELETE',
  DELETE_PRACTICE_SUCCESS: 'SUPERADMIN/PRACTICES/DELETE_SUCCESS',
  UPDATE_PRACTICE: 'SUPERADMIN/PRACTICES/UPDATE',
  SET_SELECTED_PRACTICE: 'SUPERADMIN/PRACTICES/SET_SELECTED',
  SEARCH_PRACTICES: 'SUPERADMIN/PRACTICES/SEARCH',
  FILTER_PRACTICES: 'SUPERADMIN/PRACTICES/FILTER',
} as const;

export const SUPERADMIN_USERS_CONSTANTS = {
  FETCH_USERS: 'SUPERADMIN/USERS/FETCH',
  FETCH_USERS_SUCCESS: 'SUPERADMIN/USERS/FETCH_SUCCESS',
  FETCH_USERS_FAILURE: 'SUPERADMIN/USERS/FETCH_FAILURE',
  UPDATE_USER: 'SUPERADMIN/USERS/UPDATE',
  DELETE_USER: 'SUPERADMIN/USERS/DELETE',
  SET_SELECTED_USER: 'SUPERADMIN/USERS/SET_SELECTED',
} as const;

export const SUPERADMIN_ANALYTICS_CONSTANTS = {
  FETCH_ANALYTICS: 'SUPERADMIN/ANALYTICS/FETCH',
  FETCH_ANALYTICS_SUCCESS: 'SUPERADMIN/ANALYTICS/FETCH_SUCCESS',
  FETCH_ANALYTICS_FAILURE: 'SUPERADMIN/ANALYTICS/FETCH_FAILURE',
  FETCH_REVENUE_STATS: 'SUPERADMIN/ANALYTICS/FETCH_REVENUE',
  FETCH_USER_STATS: 'SUPERADMIN/ANALYTICS/FETCH_USER_STATS',
  FETCH_APPOINTMENT_STATS: 'SUPERADMIN/ANALYTICS/FETCH_APPOINTMENT_STATS',
  SET_DATE_RANGE: 'SUPERADMIN/ANALYTICS/SET_DATE_RANGE',
} as const;

export const SUPERADMIN_SETTINGS_CONSTANTS = {
  FETCH_SETTINGS: 'SUPERADMIN/SETTINGS/FETCH',
  FETCH_SETTINGS_SUCCESS: 'SUPERADMIN/SETTINGS/FETCH_SUCCESS',
  UPDATE_SETTINGS: 'SUPERADMIN/SETTINGS/UPDATE',
  UPDATE_SETTINGS_SUCCESS: 'SUPERADMIN/SETTINGS/UPDATE_SUCCESS',
} as const;

export const SUPERADMIN_DASHBOARD_CONSTANTS = {
  FETCH_DASHBOARD_DATA: 'SUPERADMIN/DASHBOARD/FETCH',
  FETCH_DASHBOARD_DATA_SUCCESS: 'SUPERADMIN/DASHBOARD/FETCH_SUCCESS',
} as const;
