export const USER_AUTH_CONSTANTS = {
  LOGIN_REQUEST: 'USER/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER/LOGIN_FAILURE',
  LOGOUT: 'USER/LOGOUT',
  REGISTER_REQUEST: 'USER/REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER/REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER/REGISTER_FAILURE',
  SET_USER: 'USER/SET_USER',
  UPDATE_USER: 'USER/UPDATE_USER',
  SET_LOADING: 'USER/SET_LOADING',
  CLEAR_ERROR: 'USER/CLEAR_ERROR',
} as const;

export const USER_APPOINTMENT_CONSTANTS = {
  FETCH_APPOINTMENTS: 'USER/APPOINTMENTS/FETCH',
  FETCH_APPOINTMENTS_SUCCESS: 'USER/APPOINTMENTS/FETCH_SUCCESS',
  FETCH_APPOINTMENTS_FAILURE: 'USER/APPOINTMENTS/FETCH_FAILURE',
  CREATE_APPOINTMENT: 'USER/APPOINTMENTS/CREATE',
  CREATE_APPOINTMENT_SUCCESS: 'USER/APPOINTMENTS/CREATE_SUCCESS',
  CREATE_APPOINTMENT_FAILURE: 'USER/APPOINTMENTS/CREATE_FAILURE',
  CANCEL_APPOINTMENT: 'USER/APPOINTMENTS/CANCEL',
  CANCEL_APPOINTMENT_SUCCESS: 'USER/APPOINTMENTS/CANCEL_SUCCESS',
  CANCEL_APPOINTMENT_FAILURE: 'USER/APPOINTMENTS/CANCEL_FAILURE',
  UPDATE_APPOINTMENT: 'USER/APPOINTMENTS/UPDATE',
  SET_SELECTED_APPOINTMENT: 'USER/APPOINTMENTS/SET_SELECTED',
} as const;

export const USER_NOTIFICATION_CONSTANTS = {
  FETCH_NOTIFICATIONS: 'USER/NOTIFICATIONS/FETCH',
  FETCH_NOTIFICATIONS_SUCCESS: 'USER/NOTIFICATIONS/FETCH_SUCCESS',
  FETCH_NOTIFICATIONS_FAILURE: 'USER/NOTIFICATIONS/FETCH_FAILURE',
  MARK_AS_READ: 'USER/NOTIFICATIONS/MARK_AS_READ',
  MARK_ALL_AS_READ: 'USER/NOTIFICATIONS/MARK_ALL_AS_READ',
  DELETE_NOTIFICATION: 'USER/NOTIFICATIONS/DELETE',
} as const;

export const USER_FAMILY_CONSTANTS = {
  FETCH_FAMILY_MEMBERS: 'USER/FAMILY/FETCH',
  FETCH_FAMILY_MEMBERS_SUCCESS: 'USER/FAMILY/FETCH_SUCCESS',
  FETCH_FAMILY_MEMBERS_FAILURE: 'USER/FAMILY/FETCH_FAILURE',
  ADD_FAMILY_MEMBER: 'USER/FAMILY/ADD',
  ADD_FAMILY_MEMBER_SUCCESS: 'USER/FAMILY/ADD_SUCCESS',
  ADD_FAMILY_MEMBER_FAILURE: 'USER/FAMILY/ADD_FAILURE',
  UPDATE_FAMILY_MEMBER: 'USER/FAMILY/UPDATE',
  UPDATE_FAMILY_MEMBER_SUCCESS: 'USER/FAMILY/UPDATE_SUCCESS',
  DELETE_FAMILY_MEMBER: 'USER/FAMILY/DELETE',
  DELETE_FAMILY_MEMBER_SUCCESS: 'USER/FAMILY/DELETE_SUCCESS',
} as const;
